/// <reference types="vite/client" />
/// <reference types="@webgpu/types" />

// Type declarations for the WASM core module.
// The implementation is generated by wasm-pack into crates/core/pkg/.
// Keep in sync with the #[wasm_bindgen] exports in crates/core/src/lib.rs.
declare module 'core' {
  /** Called automatically on WASM module instantiation. */
  export function init(): void
  /** Returns a greeting string produced by Rust/WASM. */
  export function greet(name: string): string
}
